services:
  frontend:
    build:
      context: ./web
      target: base
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    environment:
      WATCHPACK_POLLING: "true"
    command: npm run dev -- --hostname 0.0.0.0 --port 3000

  backend:
    build:
      context: ./backend
      target: builder
    volumes:
      - ./backend:/app
    command: go run cmd/api/main.go
